# travis build for k3b-geoHelper
language: android
android:
  components:
    - build-tools-23.0.1
    - android-21
    - add-on
    - extra

before_install:
 - chmod +x gradlew

script:
  - ./gradlew -d assemble libIcsJ2se:test libIcsJ2se:jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
